### ISSUE TITLE
[BUG] Interrupt Speech with Force Insert and Control Pad not working (v3.1.3.)

### ISSUE THREAD

**Issue by qwsrkiwi** [MayouKurayami/KK_HAutoSets#1]
I'm having an issue with v3.1.3 where the interrupt options don't work at all the other options work fine however.
I updated to HF Patch v3.4 yesterday and have been trying to troubleshoot the issue myself with no luck. Plugin was working fine beforehand (although it was v3.1.1 and I was on HF Patch v3.3).

**Comment by MayouKurayami** [comment]
This is probably caused by the "Experimental performance optimizations" option introduced in HF Patch v3.4, which is checked by default.

Just to be sure, can you upload *output_log.txt*, found at the root directory of KK, right after you experience the issue?

**Comment by qwsrkiwi** [comment]
[output_log.txt](https://github.com/MayouKurayami/KK_HSceneOptions/files/5503108/output_log.txt)
