### ISSUE TITLE
[BUG] HSceneOptions will bring framerate down when cumming outside, regardless of whether cum is set to fancy, simple, or even off, and regardless of position

### ISSUE THREAD

**Issue by ghost** [MayouKurayami/KK_HAutoSets#2]

**Comment by MayouKurayami** [comment]
- If you remove HSceneOptions, does the problem persist?

- Do you have a plugin called KK_LewdCrest installed?

**Comment by ghost** [comment]
Removing HSceneOptions fixes the issue.
I do not have KK_LewdCrest installed.

EDIT: This occurs in a fresh HF Patch 3.4 install, with no other plugins installed.

EDIT2: Also, is it normal that the cumming animation only lasts for a split second, then it transitions to the afterglow? The only setting I've changed so far is "mute all spoken lines."

**Comment by MayouKurayami** [comment]
HF Patch 3.4 installs an "_Experimental performance optimization_" by default, which breaks HSceneOptions.
I am working on a fix.

**Comment by ghost** [comment]
Thank you, keep up the fantastic work! Looking forward to the fix.

**Comment by ghost** [comment]
Sorry to bother you again, I just installed HF 3.5 which does not have experimental performance improvements; so far everything is fine but setting "mute all spoken lines" causes the cumming/climax animation to skip, but only during penetration, is this normal?

**Comment by MayouKurayami** [comment]
What exactly do you mean by "_cumming/climax animation_"?
Do you mean the fast piston animation right before ejaculation, or the ejaculation animation itself (with liquid sound effects)?

**Comment by ghost** [comment]
The ejaculation animation itself with the liquid sound effects. Also, with your plugin installed if I cum inside, liquid no longer leaks out when pulling out, with fancy 3D cum enabled.

**Comment by MayouKurayami** [comment]
> The ejaculation animation itself with the liquid sound effects. Also, with your plugin installed if I cum inside, liquid no longer leaks out when pulling out, with fancy 3D cum enabled.

I do not observe this issue or the framerate issue anymore with the latest release (3.2.0) and HF Patch 3.7.


> Sorry to bother you again, I just installed HF 3.5 which does not have experimental performance improvements; so far everything is fine but setting "mute all spoken lines" causes the cumming/climax animation to skip, but only during penetration, is this normal?

The game determines the duration of precum and orgasm by the girl's speech.
As a result, when all speech is muted precum or orgasm may end too quickly.
To mitigate this issue, try setting the *Precum Timer* to a few seconds of your liking.
I've added this note in the readme and the tooltips.
