### ISSUE TITLE
[BUG] Interrupt Speech feature no longer working after updating to HF Patch v3.5

### ISSUE THREAD

**Issue by mjnko1988** [MayouKurayami/KK_HAutoSets#3]
As the title says, I was using HF Patch v3.4 and mostly updated the mods I know from the back of my head and that function was working fine, but after I updated to HF Patch v3.5 I have noticed that function has stopped working.

I'm using KK_HSceneOptions v3.1.3 (I'm pretty sure I was using this too back when I was at v3.4 just a few hours ago).

**Comment by MayouKurayami** [comment]
Duplicate of #1
